#!/bin/sh
# logview-uninstall.sh - Installation script for LogView 
# (c) 2006, LogView - File System Log Viewer
# This code is subject to the cpanel license. Unauthorized copying is prohibited
# more info about LogView please visit http://www.log-view.com
if [ "$UID" -ne "0" ]; then
	echo " You need to be root to run logview-uninstall script"
	exit 1
fi
if [ ! -d "/usr/local/cpanel" ]; then
	echo " Could not find the cpanel directory"
	exit 1
fi 
if [ ! -d "/usr/local/cpanel/whostmgr/docroot/themes/x" ]; then
	echo " Could not find the X theme directory"
	exit 1
fi
echo "Trying to un-install LogView..."
cd ~
if [ -d "/etc/lview" ]; then
	echo "Have to remove LogView directory..."
	rm -rfv /etc/lview
fi
if [ -d "/var/lib/lview" ]; then
	echo "Have to remove LogView Install directory..."
	rm -rfv /var/lib/lview
fi
echo "Un-Installing LogView Addon Script"
rm -rfv /usr/local/cpanel/whostmgr/docroot/cgi/logview
/usr/local/cpanel/bin/unregister_appconfig /var/cpanel/apps/lview.conf
/usr/local/cpanel/bin/unregister_appconfig /var/cpanel/apps/lview.conf
rm -fv /var/cpanel/apps/lview.conf

echo "*************************************"
echo "* LogView Un-Installation Completed *"
echo "*************************************"
